spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/liuhong
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    
    
logging:
  level:
    com: 
     xm: 
      mapper: trace
      
      
mybatis-plus:
  global-config:
    id-type: 0      